parameters:
- name: registry
  type: string
  default: ghcr
# - name: imagePrefix
#   type: string
#   default: ghcr.io

jobs:
- job: build
  displayName: Build container image
  pool:
    vmImage: 'ubuntu-latest'
  
  variables:
    repository: colindembovsky/dotnet-actions-v-pipelines-azdo
    # tagVersion: $[counter(variables['repository'], 1)]
    # tag: ${{ parameters.imagePrefix }}/$(repository):$(tagVersion)
    tag: $[counter(variables['repository'], 1)]

  steps:
  - task: Docker@2
    displayName: Login to ${{ parameters.registry }}
    inputs:
      command: login
      containerRegistry: ${{ parameters.registry }}
      
  - task: Docker@2
    displayName: Build image
    inputs:
      command: build
      repository: $(repository)
      tags: $(tag)
      Dockerfile: src/Dockerfile
      # DOCKER_BUILDKIT=0

  - bash: |
      id=$(docker images --filter "label=test=localhost" -q | head -1)
      docker create --name testcontainer $id
      docker cp testcontainer:/testresults/ .
      docker rm testcontainer
    displayName: Extract test results
  
  - task: PublishTestResults@2
    displayName: Publish test results
    inputs:
      testResultsFiles: 'test_results.xml'
      searchFolder: testresults
      failTaskOnFailedTests: true
  
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: testResults/**/coverage.cobertura.xml
      pathToSources: src/
      
  - task: Docker@2
    displayName: Push image
    inputs:
      command: push
      repository: $(repository)
      tags: $(tag)
      # DOCKER_BUILDKIT=0
