parameters:
- name: registry
  type: string
  default: ghcr
- name: repository
  type: string
- name: tag
  type: string

jobs:
- job: build
  displayName: Build container image
  pool:
    vmImage: 'ubuntu-latest'
  
  steps:
  - task: Docker@2
    displayName: Login to ${{ parameters.registry }}
    inputs:
      command: login
      containerRegistry: ${{ parameters.registry }}
      
  - task: Docker@2
    displayName: Build image
    inputs:
      command: build
      repository: ${{ parameters.repository }}
      tags: ${{ parameters.tag }}
      Dockerfile: src/Dockerfile
      buildContext: .
      arguments: --label org.opencontainers.image.source https://github.com/colindembovsky/dotnet-actions-v-pipelines

  - bash: |
      id=$(docker images --filter "label=test=localhost" -q | head -1)
      docker create --name testcontainer $id
      docker cp testcontainer:/testresults/ .
      docker rm testcontainer
    displayName: Extract test results
  
  - task: PublishTestResults@2
    displayName: Publish test results
    inputs:
      testResultsFiles: 'test_results.xml'
      searchFolder: testresults
      failTaskOnFailedTests: true
  
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: testresults/**/coverage.cobertura.xml
      pathToSources: src
      
  - task: Docker@2
    displayName: Push image
    inputs:
      command: push
      repository: ${{ parameters.repository }}
      tags: ${{ parameters.tag }}
