parameters:
- name: preBuildSteps
  type: stepList
  default: []
- name: postBuildSteps
  type: stepList
  default: []

jobs:
- job: build
  displayName: Build
  steps:
  - ${{ parameters.preBuildSteps }}
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk'
    inputs:
      version: 5.x
  - bash: |
      echo Doing main build here
    displayName: Do the build
  - ${{ parameters.postBuildSteps }}
