trigger: none

variables:
  repository: colindembovsky/dotnet-actions-v-pipelines-azdo
  tag: $[counter(variables['repository'], 1)]

stages:
- stage: build
  displayName: Build
  jobs:
  - template: ./templates/build-container.yml
    parameters:
      repository: $(repository)
      tag: $(tag)

- stage: dev
  displayName: Dev
  variables:
  - group: demo-dev
  jobs:
  - template: ./templates/deploy-aci.yml
    parameters:
      environment: dev
      image: ghcr.io/$(repository):$(tag)
      env_secret: $(secret)

- stage: prod
  displayName: Prod
  variables:
  - group: demo-prod
  jobs:
  - template: ./templates/deploy-aci.yml
    parameters:
      environment: prod
      image: ghcr.io/$(repository):$(tag)
      env_secret: $(secret)