name: Build dotnet application

inputs:
  resource_group:
    description: RG to deploy to
    type: string
  
  aci_name:
    description: Name of ACI to deploy to
    type: string
  
  image:
    description: Image to deploy
    type: string

  azure_creds:
    description: Azure credentials to log into subscription
    type: string

runs:
  using: composite
  steps:
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.azure_creds }}
    
    - name: Deploy the image
      shell: bash
      run: |
        ./infra/aci.sh ${{ inputs.resource_group }} ${{ inputs.aci_name }} ${{ inputs.image }}
