name: Build - Test - Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:
    # use reusable workflow here
    uses: colindembovsky/dotnet-actions-v-pipelines/.github/workflows/reusable-build-push-image.yml@main
    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}
  
  # have to explicity pass in environment variables
  deploy_dev:
    needs: build
    uses: ./.github/workflows/reusalbe-deploy.yml@main
    with:
      resource_group: vslive-demo-dev
      aci_name: vslive-demo-app-dev
      image: ghcr.io/${{ github.repository }}:${{ github.run_number }}
      environment: dev
    secrets:
      azure_creds: ${{ secrets.AZURE_CREDENTIALS }}
      env_secret: ${{ secrets.ENV_SECRET }}
        
  deploy_prod:
    needs: deploy_dev
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: http://vslive-demo-app-prod.southcentralus.azurecontainer.io
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/workflows/composite/deploy-steps
      with:
        resource_group: vslive-demo-prod
        aci_name: vslive-demo-app-prod
        image: ghcr.io/${{ github.repository }}:${{ github.run_number }}
        azure_creds: ${{ secrets.AZURE_CREDENTIALS }}
        env_secret: ${{ secrets.ENV_SECRET }}
