name: Build - Test - Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:
  - uses: ./.github/workflow/reusable/build-push-image.yml
    with:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}

  deploy_dev:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: http://vslive-demo-app-dev.southcentralus.azurecontainer.io
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/workflows/composite/deploy-steps
      with:
        resource_group: vslive-demo-dev
        aci_name: vslive-demo-app-dev
        image: ghcr.io/${{ github.repository }}:${{ github.run_number }}
        azure_creds: ${{ secrets.AZURE_CREDENTIALS }}
        
  deploy_prod:
    needs: deploy_dev
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: http://vslive-demo-app-prod.southcentralus.azurecontainer.io
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/workflows/composite/deploy-steps
      with:
        resource_group: vslive-demo-prod
        aci_name: vslive-demo-app-prod
        image: ghcr.io/${{ github.repository }}:${{ github.run_number }}
        azure_creds: ${{ secrets.AZURE_CREDENTIALS }}
