name: Build - Test - Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build the Docker image
      run: DOCKER_BUILDKIT=0 docker build . --file src/Dockerfile --tag ghcr.io/${{ github.repo }}:${{ github.run_number }}
    
    - name: Extract test results
      run: |
        id=$(docker images --filter "label=test=localhost" -q | head -1)
        docker create --name testcontainer $id
        docker cp testcontainer:/testresults .
        docker rm testcontainer
    
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: testresults/**/*.xml

    - name: GitHub Container Registry Login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Push the container
      run: |
        docker push ghcr.io/${{ github.repo }}:${{ github.run_number }}
