name: Publish dotnet app

on:
  workflow_call:
    inputs:
      environment:
        description: Environment to deploy to
        type: string
      url:
        decription: URL of site
        type: string
      resource_group:
        description: RG to deploy to
        type: string
      aci_name:
        description: Name of ACI to deploy to
        type: string
      image:
        description: Image to deploy
        type: string
    
    secrets:
      azure_creds:
        description: Azure credentials to log into subscription
        type: string
      env_secret:
        description: A demo secret variable
        type: string

jobs:
  deploy-${{ github.inputs.environment }}:
  environment:
    name: ${{ github.inputs.environment }}
    url: ${{ github.inputs.url }}
  steps:
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.azure_creds }}
    
    - name: Deploy the image
      id: deploystep
      shell: bash
      run: |
        ./infra/aci.sh ${{ inputs.resource_group }} ${{ inputs.aci_name }} ${{ inputs.image }} ${{ secrets.env_secret }}
