name: Publish dotnet app

on:
  workflow_call:
    inputs:
      environment:
        description: Environment to deploy to
        type: string
        required: true
      resource_group:
        description: RG to deploy to
        type: string
        required: true
      aci_name:
        description: Name of ACI to deploy to
        type: string
        required: true
      image:
        description: Image to deploy
        type: string
        required: true
    
    secrets:
      azure_creds:
        description: Azure credentials to log into subscription
        required: true
      env_secret:
        description: A demo secret variable
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.inputs.environment }}
      url: ${{ github.inputs.url }}
    steps:
    - uses: actions/checkout@v2
    
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.azure_creds }}
    
    - name: Deploy the image
      id: deploystep
      run: |
        ./infra/aci.sh ${{ inputs.resource_group }} ${{ inputs.aci_name }} ${{ inputs.image }} ${{ secrets.env_secret }}
